In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from astropy import units as u
from astropy import constants as const

In [2]:
originaldf = pd.read_csv("../../course_assignments/homework9/solar_system.csv")
print(originaldf.shape)
originaldf

(20, 11)

,Attribute,Mercury,Venus,Earth,Moon,Mars,Jupiter,Saturn,Uranus,Neptune,Pluto
0,Mass (10^24kg),0.330,4.87,5.97,0.073,0.642,1898,568,86.8,102,0.0130
1,Diameter (km),4879,12104,12756,3475,6792,142984,120536,51118,49528,2376
2,Density (kg/m^3),5429,5243,5514,3340,3934,1326,687,1270,1638,1850
3,Gravity (m/s^2),3.7,8.9,9.8,1.6,3.7,23.1,9.0,8.7,11.0,0.7
4,Escape Velocity (km/s),4.3,10.4,11.2,2.4,5.0,59.5,35.5,21.3,23.5,1.3
5,Rotation Period (hours),1407.6,-5832.5,23.9,655.7,24.6,9.9,10.7,-17.2,16.1,-153.3
6,Length of Day (hours),4222.6,2802.0,24.0,708.7,24.7,9.9,10.7,17.2,16.1,153.3
7,Distance from Sun (10^6 km),57.9,108.2,149.6,0.384,228.0,778.5,1432.0,2867.0,4515.0,5906.4
8,Perihelion (10^6 km),46.0,107.5,147.1,0.363,206.7,740.6,1357.6,2732.7,4471.1,4436.8
9,Aphelion (10^6 km),69.8,108.9,152.1,0.406,249.3,816.4,1506.5,3001.4,4558.9,7375.9
10,Orbital Period (days),88.0,224.7,365.2,27.3,687.0,4331,10747,30589,59800,90560
11,Orbital Velocity (km/s),47.4,35.0,29.8,1.0,24.1,13.1,9.7,6.8,5.4,4.7
12,Orbital Inclination (deg),7.0,3.4,0.0,5.1,1.8,1.3,2.5,0.8,1.8,17.2
13,Orbital Eccentricity,0.206,0.007,0.017,0.055,0.094,0.049,0.052,0.047,0.010,0.244
14,Obliquity to Orbit (deg),0.034,177.4,23.4,6.7,25.2,3.1,26.7,97.8,28.3,119.5
15,Mean Temperature (C),167,464,15,-20,-65,-110,-140,-195,-200,-225
16,Surface Pressure (bars),0,92,1,0,0.01,Unknown,Unknown,Unknown,Unknown,0.00001
17,Number of Moons,0,0,1,0,2,95,274,28,16,5
18,Ring System?,No,No,No,No,No,Yes,Yes,Yes,Yes,No
19,Global Magnetic Field?,Yes,No,Yes,No,No,Yes,Yes,Yes,Yes,Unknown

In [3]:
df = originaldf.set_index("Attribute").T
print(df.shape)
# df

(10, 20)

In [4]:
df.index.name = "Planet"
print(df.shape)
# df

(10, 20)

In [5]:
df.reset_index(inplace=True)
print(df.shape)
# df

(10, 21)

In [6]:
df.columns.name = None
print(df.shape)
df

(10, 21)

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57.9,46.0,...,88.0,47.4,7.0,0.206,0.034,167,0,0,No,Yes
1,Venus,4.87,12104,5243,8.9,10.4,-5832.5,2802.0,108.2,107.5,...,224.7,35.0,3.4,0.007,177.4,464,92,0,No,No
2,Earth,5.97,12756,5514,9.8,11.2,23.9,24.0,149.6,147.1,...,365.2,29.8,0.0,0.017,23.4,15,1,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,0.384,0.363,...,27.3,1.0,5.1,0.055,6.7,-20,0,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228.0,206.7,...,687.0,24.1,1.8,0.094,25.2,-65,0.01,2,No,No
5,Jupiter,1898,142984,1326,23.1,59.5,9.9,9.9,778.5,740.6,...,4331,13.1,1.3,0.049,3.1,-110,Unknown,95,Yes,Yes
6,Saturn,568,120536,687,9.0,35.5,10.7,10.7,1432.0,1357.6,...,10747,9.7,2.5,0.052,26.7,-140,Unknown,274,Yes,Yes
7,Uranus,86.8,51118,1270,8.7,21.3,-17.2,17.2,2867.0,2732.7,...,30589,6.8,0.8,0.047,97.8,-195,Unknown,28,Yes,Yes
8,Neptune,102,49528,1638,11.0,23.5,16.1,16.1,4515.0,4471.1,...,59800,5.4,1.8,0.010,28.3,-200,Unknown,16,Yes,Yes
9,Pluto,0.0130,2376,1850,0.7,1.3,-153.3,153.3,5906.4,4436.8,...,90560,4.7,17.2,0.244,119.5,-225,0.00001,5,No,Unknown

In [7]:
for name in df.columns:
    print(name)
    
c=0
for name in df.columns:
    c += 1
print(c)

Planet
Mass (10^24kg)
Diameter (km)
Density (kg/m^3)
Gravity (m/s^2)
Escape Velocity (km/s)
Rotation Period (hours)
Length of Day (hours)
Distance from Sun (10^6 km)
Perihelion (10^6 km)
Aphelion (10^6 km)
Orbital Period (days)
Orbital Velocity (km/s)
Orbital Inclination (deg)
Orbital Eccentricity
Obliquity to Orbit (deg)
Mean Temperature (C)
Surface Pressure (bars)
Number of Moons
Ring System?
Global Magnetic Field?
21

In [8]:
# 5. Answer the following

# (a) Print the shape of the DataFrame before and after transposing.
# See above

# (b) How many rows/columns are there before and after transposing?
# Before transposing the shape was 20 x 11: 20 rows and 11 columns
# After transposing the shape of the dataframe was 10 x 21: 10 rows and 21 columns

# (c) Explain what each line of code above does.
# Hint: Print the shape of the DataFrame after each line of code.
# df = df.set_index("Attribute").T 
# This set transposes the dataframe so that each planet's data is represented in a row to the right
# rather than in a column below it.
# df.index.name = "Planet"
# This adds a column title "Planet" over the planet names.
# The column title lies beneath row title "Attribute" (which describes the Attribute columns to the right)
# df.reset_index(inplace=True)
# This command adds back the indexing on the far left column (0 through 9, since there are 10 planets)
# It also shifts the top labeling, so the column titles are "Attribute", then "PLanet", then "Mass" etc.
# ("Attribute" and "Planet" are now in a line rather than one on top of another)
# df.columns.name = None
# This removed the column name "Attribute" since it is no longer needed. Each column is now properly named, 
# including the "Planet name" column in particular.

# (d) Why isn’t the new shape (11, 20)? What’s different about the structure?
# The new shape is (10 x 21) because originally there were 20 rows and 10 columns, plus one column for indexing.
# When we transpose the dataframe, rows become columns and columns become rows so now the new shape
# is 10 rows and 20 columns, and we again add on more column for the indexing.
# Thus, the final shape is 10 x 21, rather than 11 x 20.


# (e) Print the new column names.
# See above

# (f) How many columns have units? List them. How many don’t? List them.
# There are 5 column titles without units. They are:
# Planet, Orbital Eccentricity, Number of Moons, Ring System?, and Global Magnetic Field?
# There are 16 column titles with units. They are:
# Mass (10^24kg), Diameter (km), Density (kg/m^3), Gravity (m/s^2), Escape Velocity (km/s)
# Rotation Period (hours), Length of Day (hours), Distance from Sun (10^6 km), Perihelion (10^6 km)
# Aphelion (10^6 km), Orbital Period (days), Orbital Velocity (km/s), Orbital Inclination (deg)
# Obliquity to Orbit (deg), Mean Temperature (C), and Surface Pressure (bars)

# (g) Print the whole transposed DataFrame.
# See above

In [9]:
df["Planet"]
print(df["Planet"].dtypes)

for name in df.columns:
    print(df[name].dtypes)

object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object

In [10]:
for name in df.columns:
    print(df[name].apply(type))

0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Planet, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Mass (10^24kg), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Diameter (km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Density (kg/m^3), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Gravity (m/s^2), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Escape Velocity (km/s), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Rotation Period (hours), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Length of Day (hours), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Distance from Sun (10^6 km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Perihelion (10^6 km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Aphelion (10^6 km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Period (days), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Velocity (km/s), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Inclination (deg), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Eccentricity, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Obliquity to Orbit (deg), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Mean Temperature (C), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Surface Pressure (bars), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Number of Moons, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Ring System?, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Global Magnetic Field?, dtype: object

In [11]:
# (a) What types are the actual values?
# All of the values are stored in the dataframe as strings, although they are essentially numbers.
# (b) Why is storing numeric values as string a problem for data analysis?
# Storing numerical values as strings creates problems for data analysis because they are not compatible
# with most arithmetic operations and functions/commands that use them. You are unable to, for 
# example, double each value in a column, or take the average of two columns.

In [12]:
for name in df.columns:
    if name != "Planet" and name !="Ring System?" and name != "Global Magnetic Field?":
        df[name] = pd.to_numeric(df[name], errors="coerce")

In [13]:
for name in df.columns:
    print(df[name].dtypes)

object
float64
int64
int64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
int64
float64
int64
object
object

In [14]:
# 2.1.3.3 Answer the following:
# (a) What are the three different data types now in the DataFrame?
# The three different data types in the Data Frame are objects, floats (float64), and integers (int64).
# (b) Define each one (e.g. float64).
# An object is an instance of class, which contain data and perform actions. A float64 is a 
# decimal value, which is comprises of 64 bits (refering to the size of the data). An int64 is 
# an integer value (a whole number) also comprised of 64 bits of memory.
# (c) Which columns are still object, and why?
# The columns that are still object are Planet, Ring System?, and Global Magnetic Field?. 
# These columns still have the "object" datatype because they hold strings, rather than numerical
# values like floats or integers.

for name in df.columns:
    type = df[name].dtypes
    if type == object:
        print(name)

Planet
Ring System?
Global Magnetic Field?

In [15]:
def attach_units(original_col, new_col, unit):
    new_values = []
    for value in df[original_col]:
        value = value * unit
        new_values.append(value)
    df[original_col] = new_values
    df.rename(columns={original_col: new_col}, inplace=True)

attach_units("Mass (10^24kg)", "Mass (kg)", 1e24 * u.kg)
print(df["Mass (kg)"])

0                   3.3e+23 kg
1                  4.87e+24 kg
2     5.969999999999999e+24 kg
3                   7.3e+22 kg
4                  6.42e+23 kg
5                 1.898e+27 kg
6                  5.68e+26 kg
7                  8.68e+25 kg
8    1.0199999999999999e+26 kg
9                   1.3e+22 kg
Name: Mass (kg), dtype: object

In [16]:
# for name in df.columns:
#     print(name)

semi_major_axis = []
for peri, aphe in zip(df["Perihelion (10^6 km)"], df["Aphelion (10^6 km)"]):
    sma = (peri + aphe) / 2
    sma = sma * 1e6 * u.km
    semi_major_axis.append(sma)

In [17]:
df.insert(11, "Semi-Major Axis (km)", semi_major_axis, allow_duplicates=False)

for name in df.columns:
    print(name)

Planet
Mass (kg)
Diameter (km)
Density (kg/m^3)
Gravity (m/s^2)
Escape Velocity (km/s)
Rotation Period (hours)
Length of Day (hours)
Distance from Sun (10^6 km)
Perihelion (10^6 km)
Aphelion (10^6 km)
Semi-Major Axis (km)
Orbital Period (days)
Orbital Velocity (km/s)
Orbital Inclination (deg)
Orbital Eccentricity
Obliquity to Orbit (deg)
Mean Temperature (C)
Surface Pressure (bars)
Number of Moons
Ring System?
Global Magnetic Field?

In [18]:
print(df["Semi-Major Axis (km)"])

0      57900000.0 km
1     108200000.0 km
2     149600000.0 km
3        384500.0 km
4     228000000.0 km
5     778500000.0 km
6    1432050000.0 km
7    2867050000.0 km
8    4515000000.0 km
9    5906350000.0 km
Name: Semi-Major Axis (km), dtype: object

In [19]:
print(df["Orbital Period (days)"])

orbital_period_yrs = []
for value in df["Orbital Period (days)"]:
    value_d = value * u.d
    value_yr = value_d.to(u.yr)
    orbital_period_yrs.append(value_yr)
df["Orbital Period (days)"] = orbital_period_yrs
df.rename(columns={"Orbital Period (days)": "Orbital Period (years)"}, inplace=True)

for name in df.columns:
    print(name)

print(df["Orbital Period (years)"])

0       88.0
1      224.7
2      365.2
3       27.3
4      687.0
5     4331.0
6    10747.0
7    30589.0
8    59800.0
9    90560.0
Name: Orbital Period (days), dtype: float64
Planet
Mass (kg)
Diameter (km)
Density (kg/m^3)
Gravity (m/s^2)
Escape Velocity (km/s)
Rotation Period (hours)
Length of Day (hours)
Distance from Sun (10^6 km)
Perihelion (10^6 km)
Aphelion (10^6 km)
Semi-Major Axis (km)
Orbital Period (years)
Orbital Velocity (km/s)
Orbital Inclination (deg)
Orbital Eccentricity
Obliquity to Orbit (deg)
Mean Temperature (C)
Surface Pressure (bars)
Number of Moons
Ring System?
Global Magnetic Field?
0    0.24093086926762491 yr
1     0.6151950718685831 yr
2     0.9998631074606433 yr
3    0.07474332648870637 yr
4     1.8809034907597535 yr
5      11.85763175906913 yr
6     29.423682409308693 yr
7      83.74811772758385 yr
8     163.72347707049965 yr
9     247.93976728268308 yr
Name: Orbital Period (years), dtype: object

In [20]:
# for planet, period in zip(df["Planet"], df["Orbital Period (years)"]):
#     print(planet, period)

print(f"My favorite planet's orbital period is Pluto's, with an orbital period of {df["Orbital Period (years)"][9]:.4f}.")

My favorite planet's orbital period is Pluto's, with an orbital period of 247.9398 yr.

In [21]:
# 2.3.3
# Define AU in your own words.
# AU is a unit used to describe very big distances in space. It measures the approximate 
# distance between Earth and the Sun, about 93 million miles. 
au = const.au
print(au)
au_km = au.to(u.km)
print(au_km)
# There are 149597870.7 km in one AU.

  Name   = Astronomical Unit
  Value  = 149597870700.0
  Uncertainty  = 0.0
  Unit  = m
  Reference = IAU 2012 Resolution B2
149597870.70000002 km

In [22]:
def add_units(column_name, units):
    new_values = []
    for value in df[column_name]:
        value_units = value * units
        new_values.append(value_units)
    df[column_name] = new_values
    
def change_units(column_name, new_column_name, new_units):
    new_values = []
    for value in df[column_name]:
        new_value = value.to(new_units)
        new_values.append(new_value)
    df[column_name] = new_values
    df.rename(columns={column_name: new_column_name}, inplace=True)

In [23]:
for value in df["Diameter (km)"]:
    print(value)

add_units("Diameter (km)", u.km)

for value in df["Diameter (km)"]:
    print(value)

4879
12104
12756
3475
6792
142984
120536
51118
49528
2376
4879.0 km
12104.0 km
12756.0 km
3475.0 km
6792.0 km
142984.0 km
120536.0 km
51118.0 km
49528.0 km
2376.0 km

In [24]:
change_units("Diameter (km)", "Diameter (AU)", u.au)

for value in df["Diameter (AU)"]:
    print(value)

3.261410056954775e-05 AU
8.091024252793726e-05 AU
8.526859333165629e-05 AU
2.3228940249882847e-05 AU
4.540171573444728e-05 AU
0.0009557890050904314 AU
0.0008057333933697493 AU
0.0003417027245161184 AU
0.0003310742309917116 AU
1.588257900250983e-05 AU

In [25]:
# for value in df["Escape Velocity (km/s)"]:
#     print(value)

add_units("Escape Velocity (km/s)", u.km)
change_units("Escape Velocity (km/s)", "Escape Velocity (AU/s)", u.au)

new_values = []
for value in df["Escape Velocity (AU/s)"]:
    value_units = value /  u.s
    new_values.append(value_units)
df["Escape Velocity (AU/s)"] = new_values

# for value in df["Escape Velocity (AU/s)"]:
#     print(value)

In [26]:
def add_1e6km(column_name):
    new_values = []
    for value in df[column_name]:
        value_units = value * 1e6 * u.km
        new_values.append(value_units)
    df[column_name] = new_values

add_1e6km("Distance from Sun (10^6 km)")

change_units("Distance from Sun (10^6 km)", "Distance from Sun (AU)", u.au)

for value in df["Distance from Sun (AU)"]:
    print(value)

0.387037594379343 AU
0.7232723266294458 AU
1.0000142334913595 AU
0.002566881454951083 AU
1.5240858638772057 AU
5.2039510746859845 AU
9.572328759088414 AU
19.164711279543635 AU
30.180910857042033 AU
39.48184537896635 AU

In [27]:
add_1e6km("Perihelion (10^6 km)")
change_units("Perihelion (10^6 km)", "Perihelion (AU)", u.au)

add_1e6km("Aphelion (10^6 km)")
change_units("Aphelion (10^6 km)", "Aphelion (AU)", u.au)    

for value in df["Perihelion (AU)"]:
    print(value)

for value in df["Aphelion (AU)"]:
    print(value)

0.3074910076243485 AU
0.7185931156438579 AU
0.9833027656856883 AU
0.0024265051253834456 AU
1.3817041581728877 AU
4.950605222752011 AU
9.074995477191642 AU
18.26697122902298 AU
29.887457482374447 AU
29.658176144080638 AU
0.46658418113433753 AU
0.7279515376150337 AU
1.0167257012970305 AU
0.002713942371640989 AU
1.6664675695815234 AU
5.457296926619959 AU
10.070330499697413 AU
20.06311978877651 AU
30.474364231709618 AU
49.30484615513983 AU

In [30]:
for value in df["Semi-Major Axis (km)"]:
    print(value)

change_units("Semi-Major Axis (km)", "Semi-Major Axis (AU)", u.au)

for value in df["Semi-Major Axis (AU)"]:
    print(value)

57900000.0 km
108200000.0 km
149600000.0 km
384500.0 km
228000000.0 km
778500000.0 km
1432050000.0 km
2867050000.0 km
4515000000.0 km
5906350000.0 km
0.387037594379343 AU
0.7232723266294458 AU
1.0000142334913595 AU
0.0025702237485122174 AU
1.5240858638772057 AU
5.2039510746859845 AU
9.572662988444527 AU
19.16504550889975 AU
30.180910857042033 AU
39.481511149610235 AU

In [33]:
for value in df["Orbital Velocity (km/s)"]:
    print(value)

add_units("Orbital Velocity (km/s)", u.km)
change_units("Orbital Velocity (km/s)", "Orbital Velocity (AU/s)", u.au)

new_values = []
for value in df["Orbital Velocity (AU/s)"]:
    value_units = value / u.s
    new_values.append(value_units)
    
df["Orbital Velocity (AU/s)"] = new_values

for value in df["Orbital Velocity (AU/s)"]:
    print(value)

47.4
35.0
29.8
1.0
24.1
13.1
9.7
6.8
5.4
4.7
3.1684942959552433e-07 AU / s
2.339605492793956e-07 AU / s
1.9920069624359968e-07 AU / s
6.684587122268446e-09 AU / s
1.6109854964666954e-07 AU / s
8.756809130171664e-08 AU / s
6.484049508600391e-08 AU / s
4.5455192431425426e-08 AU / s
3.609677046024961e-08 AU / s
3.14175594746617e-08 AU / s

In [34]:
for name in df.columns:
    print(name)

Planet
Mass (kg)
Diameter (AU)
Density (kg/m^3)
Gravity (m/s^2)
Escape Velocity (AU/s)
Rotation Period (hours)
Length of Day (hours)
Distance from Sun (AU)
Perihelion (AU)
Aphelion (AU)
Semi-Major Axis (AU)
Orbital Period (years)
Orbital Velocity (AU/s)
Orbital Inclination (deg)
Orbital Eccentricity
Obliquity to Orbit (deg)
Mean Temperature (C)
Surface Pressure (bars)
Number of Moons
Ring System?
Global Magnetic Field?

In [35]:
for planet in df["Planet"]:
    print(planet)

Mercury
Venus
Earth
Moon
Mars
Jupiter
Saturn
Uranus
Neptune
Pluto

In [38]:
print("Pluto has the following specs:")
for column in ["Diameter (AU)", "Escape Velocity (AU/s)", "Distance from Sun (AU)", "Perihelion (AU)", "Aphelion (AU)", "Semi-Major Axis (AU)", "Orbital Velocity (AU/s)"]:
    print(f"{column}: {df[column][9]}")

Pluto has the following specs:
Diameter (AU): 1.588257900250983e-05 AU
Escape Velocity (AU/s): 8.68996325894898e-09 AU / s
Distance from Sun (AU): 39.48184537896635 AU
Perihelion (AU): 29.658176144080638 AU
Aphelion (AU): 49.30484615513983 AU
Semi-Major Axis (AU): 39.481511149610235 AU
Orbital Velocity (AU/s): 3.14175594746617e-08 AU / s

In [39]:
df.to_csv("Units.csv", index=False)